theme: jekyll-theme-cayman
title: 'Choreographer: Learning and <br> Adapting Skills in Imagination'
description:
- Pietro Mazzaglia, Tim Verbelen, Bart Dhoedt, Alexandre Lacoste, Sai Rajeswar <br>
- Presented at Offline RL (oral) and Deep RL workshop @ NeurIPS 2022 <br>
buttons:
  Arxiv version coming soon: ''
  Workshop Paper: 'https://openreview.net/pdf?id=BxYsP-7ggf'
google_analytics: G-ZPNZSNQH2T 